server.port=8081

# DataSource MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/fintech_usuarios?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# App name
spring.application.name=ms-usuarios

# CORS
cors.allowed-origins=http://localhost:4200

# Mail SMTP
spring.mail.host=${SMTP_HOST:localhost}
spring.mail.port=${SMTP_PORT:1025}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS:false}
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Password recovery
app.mail.from=${APP_MAIL_FROM:no-reply@fintech.pe}
app.password-reset.frontend-url=${PASSWORD_RESET_FRONTEND_URL:http://localhost:4200/reset-password}
app.password-reset.expiration-minutes=${PASSWORD_RESET_EXPIRATION_MINUTES:30}
